export const oracleSteps = [
  {
    id: "archetype",
    title: "Soul Archetype Discovery",
    question: "Which essence resonates with your soul's everyday rhythm?",
    subtitle: "Feel into your deepest nature...",
    options: [
      { value: "contemplative", label: "Reflector", emoji: "🧘", description: "Calm and enjoys solitude", colors: "from-blue-400 to-teal-500", bgColor: "bg-blue-500/20" },
      { value: "spark", label: "Spark", emoji: "🎇", description: "Energetic and loves socializing", colors: "from-orange-400 to-red-500", bgColor: "bg-orange-500/20" },
      { value: "seeker", label: "Seeker", emoji: "🧠", description: "Curious and loves exploring", colors: "from-purple-400 to-indigo-500", bgColor: "bg-purple-500/20" },
      { value: "creator", label: "Creator", emoji: "🎨", description: "Creative and loves making things", colors: "from-pink-400 to-purple-500", bgColor: "bg-pink-500/20" },
      { value: "adventurer", label: "Adventurer", emoji: "🌍", description: "Bold and loves new experiences", colors: "from-green-400 to-blue-500", bgColor: "bg-green-500/20" },
      { value: "nurturer", label: "Nurturer", emoji: "🤗", description: "Caring and enjoys helping others", colors: "from-yellow-400 to-pink-400", bgColor: "bg-yellow-500/20" },
      { value: "organizer", label: "Organizer", emoji: "🗂️", description: "Practical and likes planning", colors: "from-gray-400 to-blue-400", bgColor: "bg-gray-500/20" },
      { value: "dreamer", label: "Dreamer", emoji: "💭", description: "Imaginative and loves to daydream", colors: "from-cyan-400 to-purple-400", bgColor: "bg-cyan-500/20" },
    ],
  },
  {
    id: "mood",
    title: "Present Moment Witness",
    question: "What energy flows through you in this moment?",
    subtitle: "Honor your current state...",
    options: [
      { value: "flowing", label: "Relaxed", emoji: "🛀", description: "Relaxed and easygoing", colors: "from-blue-300 to-green-400", bgColor: "bg-blue-400/20" },
      { value: "refuge", label: "Restful", emoji: "🌙", description: "Stressed and need a break", colors: "from-orange-400 to-red-400", bgColor: "bg-orange-400/20" },
      { value: "spark", label: "Excited", emoji: "🎉", description: "Bored, need excitement", colors: "from-purple-400 to-yellow-400", bgColor: "bg-purple-400/20" },
      { value: "deep", label: "Deep", emoji: "🌊", description: "Reflective or introspective", colors: "from-indigo-500 to-gray-600", bgColor: "bg-indigo-500/20" },
      { value: "joyful", label: "Joyful", emoji: "🌈", description: "Feeling happy and uplifted", colors: "from-yellow-300 to-pink-400", bgColor: "bg-yellow-300/20" },
      { value: "anxious", label: "Anxious", emoji: "⏳", description: "Feeling worried or uneasy", colors: "from-red-300 to-gray-400", bgColor: "bg-red-300/20" },
      { value: "curious", label: "Curious", emoji: "🔍", description: "Eager to learn or discover", colors: "from-green-300 to-blue-400", bgColor: "bg-green-300/20" },
      { value: "content", label: "Content", emoji: "🪷", description: "At peace with the present moment", colors: "from-blue-200 to-green-200", bgColor: "bg-blue-200/20" },
    ],
  },
  {
    id: "philosophy",
    title: "Journey Philosophy",
    question: "How does your spirit prefer to dance with the unknown?",
    subtitle: "Choose your sacred approach...",
    options: [
      { value: "architect", label: "Planner", emoji: "📐", description: "Well-planned and detailed", colors: "from-gray-400 to-blue-500", bgColor: "bg-gray-500/20" },
      { value: "wanderer", label: "Explorer", emoji: "🧭", description: "Spontaneous and open", colors: "from-purple-400 to-pink-500", bgColor: "bg-purple-500/20" },
      { value: "harmonizer", label: "Balancer", emoji: "⚖️", description: "Balanced mix of both", colors: "from-green-400 to-teal-500", bgColor: "bg-green-500/20" },
      { value: "dreamer", label: "Visionary", emoji: "🔮", description: "Imaginative and intuitive", colors: "from-cyan-400 to-purple-500", bgColor: "bg-cyan-500/20" },
      { value: "adventurer", label: "Adventurer", emoji: "🏔️", description: "Loves new and bold experiences", colors: "from-orange-400 to-yellow-500", bgColor: "bg-orange-500/20" },
      { value: "connector", label: "Connector", emoji: "🤝", description: "Enjoys bringing people together", colors: "from-pink-400 to-yellow-400", bgColor: "bg-pink-500/20" },
      { value: "seeker", label: "Seeker", emoji: "🔍", description: "Always searching for meaning", colors: "from-blue-400 to-indigo-500", bgColor: "bg-blue-500/20" },
      { value: "creator", label: "Creator", emoji: "🎨", description: "Inventive and loves making things", colors: "from-green-400 to-blue-400", bgColor: "bg-green-500/20" },
    ],
  },
  {
    id: "intention",
    title: "Emotional Intention",
    question: "Should this journey honor your current energy or transform it?",
    subtitle: "Set your soul's intention...",
    options: [
      { value: "honor", label: "Harmony", emoji: "🎼", description: "Match current mood", colors: "from-blue-400 to-purple-500", bgColor: "bg-blue-500/20" },
      { value: "transform", label: "Transformation", emoji: "🦋", description: "Shift current mood", colors: "from-orange-400 to-pink-500", bgColor: "bg-orange-500/20" },
      { value: "discover", label: "Discovery", emoji: "🧭", description: "I'm not sure yet", colors: "from-yellow-400 to-purple-500", bgColor: "bg-yellow-500/20" },
      { value: "heal", label: "Healing", emoji: "🌿", description: "Soothe and restore your energy", colors: "from-green-400 to-teal-500", bgColor: "bg-green-500/20" },
      { value: "growth", label: "Growth", emoji: "🌱", description: "Expand your horizons", colors: "from-green-300 to-yellow-400", bgColor: "bg-green-300/20" },
      { value: "adventure", label: "Adventure", emoji: "🚀", description: "Embrace the unknown", colors: "from-pink-400 to-blue-400", bgColor: "bg-pink-400/20" },
      { value: "gratitude", label: "Gratitude", emoji: "🙏", description: "Appreciate the present", colors: "from-yellow-300 to-orange-400", bgColor: "bg-yellow-300/20" },
      { value: "connection", label: "Connection", emoji: "🤝", description: "Deepen bonds with others", colors: "from-blue-400 to-green-400", bgColor: "bg-blue-400/20" },
    ],
  },
  {
    id: "destinations",
    title: "Soul Destinations",
    question: "Which realms call to your spirit?",
    subtitle: "Select all that resonate. You can choose multiple interests to shape your journey.",
    multiSelect: true,
    options: [
      { value: "nature", label: "Nature", emoji: "🏞️", description: "Mountains, forests, oceans" },
      { value: "culture", label: "Culture", emoji: "🌏", description: "Local customs and ways of life" },
      { value: "food", label: "Food", emoji: "🍜", description: "Culinary quests and foodie explorations" },
      { value: "sports", label: "Sports", emoji: "⚽", description: "Active adventures and games" },
      { value: "architecture", label: "Architecture", emoji: "🏙️", description: "Buildings, design, cityscapes" },
      { value: "art", label: "Art & Exhibits", emoji: "🖼️", description: "Galleries, exhibitions, creative spaces" },
      { value: "history", label: "History", emoji: "📜", description: "Historical sites and stories" },
      { value: "landmarks", label: "Landmarks", emoji: "🗽", description: "Famous places and icons" },
      { value: "museums", label: "Museums", emoji: "🏛️", description: "Collections and exhibitions" },
      { value: "nightlife", label: "Night Life", emoji: "🌃", description: "Bars, clubs, and evening fun" },
      { value: "shopping", label: "Shopping", emoji: "🛍️", description: "Markets, malls, unique finds" },
      { value: "wellness", label: "Wellness & Spa", emoji: "💆‍♂️", description: "Relaxation, spa, self-care" },
      { value: "adventure", label: "Adventure", emoji: "🧗‍♂️", description: "Thrilling outdoor activities" },
      { value: "beaches", label: "Beaches", emoji: "🏖️", description: "Sun, sand, and sea" },
      { value: "wildlife", label: "Wildlife", emoji: "🦁", description: "Animals, safaris, zoos" },
      { value: "festivals", label: "Festivals", emoji: "🎉", description: "Cultural and music festivals" },
      { value: "technology", label: "Technology", emoji: "💻", description: "Innovation, science centers" },
      { value: "literature", label: "Literature", emoji: "📚", description: "Bookstores, libraries, literary tours" },
      { value: "music", label: "Music", emoji: "🎵", description: "Concerts, live music, music history" },
      { value: "spirituality", label: "Spirituality", emoji: "🕉️", description: "Temples, meditation, sacred sites" },
      { value: "science", label: "Science & Innovation", emoji: "🔬", description: "Museums, labs, discoveries" },
      { value: "family", label: "Family Fun", emoji: "👨‍👩‍👧‍👦", description: "Theme parks, family activities" },
      { value: "photography", label: "Photography", emoji: "📷", description: "Scenic spots, photo walks" },
      { value: "gardens", label: "Gardens & Parks", emoji: "🌳", description: "Botanical gardens, city parks" },
      { value: "cruises", label: "Cruises", emoji: "🚢", description: "River and sea cruises" },
    ],
  },
  {
    id: "practical",
    title: "Journey Logistics",
    question: "Finally, let's ground your journey in reality.",
    subtitle: "Define the canvas for your adventure...",
    practical: true,
  },
] 